### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by MrFallen** [protonemedia/inertiajs-tables-laravel-query-builder#32]
Is this package does not work with Inertia JS?

`E:\Projects\dymlab>node public/js/ssr.js
Starting SSR server...
Server started.
E:\Projects\dymlab\node_modules\@protonemedia\inertiajs-tables-laravel-query-builder\js\index.js:1
import iwqb from './InteractsWithQueryBuilder.vue';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.@protonemedia/inertiajs-tables-laravel-query-builder (E:\Projects\dymlab\public\js\ssr.js:13219:18)
    at __webpack_require__ (E:\Projects\dymlab\public\js\ssr.js:13287:41)
    at Object../node_modules/babel-loader/lib/index.js??clonedRuleSet-5.use[0]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./resources/js/Pages/Dashboard.vue?vue&type=script&lang=js (E:\Projects\dymlab\public\js\ssr.js:1466:110)
ReferenceError: Cannot access '__WEBPACK_DEFAULT_EXPORT__' before initialization
    at Module.default (E:\Projects\dymlab\public\js\ssr.js:11202:42)
    at E:\Projects\dymlab\node_modules\@inertiajs\inertia-vue3\dist\index.js:1:9011
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
ReferenceError: Cannot access '__WEBPACK_DEFAULT_EXPORT__' before initialization
    at Module.default (E:\Projects\dymlab\public\js\ssr.js:11202:42)
    at E:\Projects\dymlab\node_modules\@inertiajs\inertia-vue3\dist\index.js:1:9011
    at processTicksAndRejections (internal/process/task_queues.js:97:5)`

**Comment by pascalbaljet** [comment]
What's inside `ssr.js`? How can I replicate this error?

**Comment by John94php** [comment]
if you're using 
<script>
</script>

try to use
<script type='module'></script>

**Comment by daninfocus** [comment]
I had this problem, try deleting node_modules directory and reinstalling all the packages again with 
`npm install`
I also tried composer install as well, if your problem persists.
